version: "3"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  # make sure that you specify correct volume to be mounted
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=accesskey
      - MINIO_ROOT_PASSWORD=secretkey
    volumes:
      - ./data1/minio:/data
    ports:
      - "9000:9000"
    command: server /data

  hive-metastore:
    build: .
    image: hive-metastore:latest
    ports:
      - "9083:9083"
    depends_on:
      - mariadb

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 accesskey secretkey;
      /usr/bin/mc mb myminio/spark;
      /usr/bin/mc policy set public myminio/spark;
      exit 0;
      "